spring.datasource.url=jdbc:mysql://mysql:3306/job_tracker_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:3600000}

reminder.scheduler.delay=${REMINDER_SCHEDULER_DELAY:60000}

server.port=8080